#!/usr/bin/env python3

# -------------------------------------------------------------------------
# MEGAHIT
# Copyright (C) 2014 - 2015 The University of Hong Kong & L3 Bioinformatics Limited
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -------------------------------------------------------------------------



import errno
import ctypes
import getopt
import glob
import json
import logging
import multiprocessing
import os
import stat
import shutil
import signal
import subprocess
import sys
import tempfile
import time
import math

logger = logging.getLogger(__name__)
_numa_reservation = None

_usage_message = '''
contact: Dinghua Li <voutcn@gmail.com>

Usage:
  megahit [options] {{-1 <pe1> -2 <pe2> | --12 <pe12> | -r <se>}} [-o <out_dir>]

  Input options that can be specified for multiple times (supporting plain text and gz/bz2 extensions)
    -1                       <pe1>          comma-separated list of fasta/q paired-end #1 files, paired with files in <pe2>
    -2                       <pe2>          comma-separated list of fasta/q paired-end #2 files, paired with files in <pe1>
    --12                     <pe12>         comma-separated list of interleaved fasta/q paired-end files
    -r/--read                <se>           comma-separated list of fasta/q single-end files

Optional Arguments:
  Basic assembly options:
    --min-count              <int>          minimum multiplicity for filtering (k_min+1)-mers [2]
    --k-list                 <int,int,..>   comma-separated list of kmer size
                                            all must be odd, in the range 15-{0}, increment <= 28)
                                            [21,29,39,59,79,99,119,141]

  Another way to set --k-list (overrides --k-list if one of them set):
    --k-min                  <int>          minimum kmer size (<= {0}), must be odd number [21]
    --k-max                  <int>          maximum kmer size (<= {0}), must be odd number [141]
    --k-step                 <int>          increment of kmer size of each iteration (<= 28), must be even number [10]

  Advanced assembly options:
    --no-mercy                              do not add mercy kmers
    --bubble-level           <int>          intensity of bubble merging (0-2), 0 to disable [2]
    --merge-level            <l,s>          merge complex bubbles of length <= l*kmer_size and similarity >= s [20,0.95]
    --prune-level            <int>          strength of low depth pruning (0-3) [2]
    --prune-depth            <int>          remove unitigs with avg kmer depth less than this value [2]
    --disconnect-ratio       <float>        disconnect unitigs if its depth is less than this ratio times 
                                            the total depth of itself and its siblings [0.1]  
    --low-local-ratio        <float>        remove unitigs if its depth is less than this ratio times
                                            the average depth of the neighborhoods [0.2]
    --max-tip-len            <int>          remove tips less than this value [2*k]
    --cleaning-rounds        <int>          number of rounds for graph cleanning [5]
    --no-local                              disable local assembly
    --kmin-1pass                            use 1pass mode to build SdBG of k_min

  Presets parameters:
    --presets                <str>          override a group of parameters; possible values:
                                            meta-sensitive: '--min-count 1 --k-list 21,29,39,49,...,129,141'
                                            meta-large: '--k-min 27 --k-max 127 --k-step 10'
                                            (large & complex metagenomes, like soil)

  Hardware options:
    -m/--memory              <float>        max memory in byte to be used in SdBG construction
                                            (if set between 0-1, fraction of the selected NUMA domain,
                                            or of the machine when automatic placement is unavailable) [0.9]
    --mem-flag               <int>          SdBG builder memory mode. 0: minimum; 1: moderate;
                                            others: use all memory specified by '-m/--memory' [1]
    -t/--num-cpu-threads     <int>          number of CPU threads [# of logical processors]
    --numa-node              <int|auto|off> explicit CPU/private-memory binding; off disables automatic placement
                                            default: coordinate local CPU placement with other instances
    --jobs-per-node          <int>          RabbitMA jobs sharing the same CPU/cache/memory allocation [1]
    --memory-budget-per-job  <float>        explicit memory cap in bytes for this job [auto]
    --no-hw-accel                           run RabbitMA without BMI2 and POPCNT hardware instructions

  Output options:
    -o/--out-dir             <string>       output directory [./megahit_out]
    --out-prefix             <string>       output prefix (the contig file will be OUT_DIR/OUT_PREFIX.contigs.fa)
    --min-contig-len         <int>          minimum length of contigs to output [200]
    --keep-tmp-files                        keep all temporary files
    --tmp-dir                <string>       set temp directory

Other Arguments:
    --continue                              continue a RabbitMA run from its last available check point.
                                            please set the output directory correctly when using this option.
    --test                                  run RabbitMA on a toy test dataset
    -h/--help                               print the usage message
    -v/--version                            print version
'''


def launch_process(*args, **kwargs):
    # A core process must retain its CPU reservation even if the launcher is
    # killed. flock releases the reservation after the last inheriting process
    # exits, without PID files, stale-process detection or a background daemon.
    if _numa_reservation is not None:
        kwargs['pass_fds'] = tuple(sorted(set(kwargs.get('pass_fds', ())) |
                                          set(_numa_reservation.fds)))
    return subprocess.Popen(*args, **kwargs)


def check_output(cmd):
    p = launch_process(cmd, stdout=subprocess.PIPE)
    out, _ = p.communicate()
    out = out.rstrip().decode('utf-8')
    assert p.wait() == 0
    return out


def abspath(path):
    return os.path.abspath(os.path.expanduser(path))


def mkdir_if_not_exists(path):
    if not os.path.exists(path):
        os.mkdir(path)


def remove_if_exists(file_name):
    if os.path.exists(file_name):
        os.remove(file_name)


class Usage(Exception):
    def __init__(self, msg):
        self.msg = msg


class EarlyTerminate(Exception):
    def __init__(self, kmer_size):
        self.kmer_size = kmer_size


class SoftwareInfo(object):
    script_path = os.path.dirname(os.path.realpath(__file__))
    megahit_core = os.path.join(script_path, 'megahit_core')
    megahit_core_popcnt = os.path.join(script_path, 'megahit_core_popcnt')
    megahit_core_no_hw_accel = os.path.join(script_path, 'megahit_core_no_hw_accel')

    @property
    def megahit_version(self):
        return 'RabbitMA 0.2.1 (MEGAHIT core %s)' % check_output([self.megahit_core, 'dumpversion'])

    @property
    def max_k_allowed(self):
        return int(check_output([self.megahit_core, 'kmax']))

    @property
    def usage_message(self):
        return _usage_message.format(self.max_k_allowed)


class Options:
    def __init__(self):
        self.out_dir = ''
        self.temp_dir = ''
        self.test_mode = False
        self.continue_mode = False
        self.force_overwrite = False
        self.memory = 0.9
        self.min_contig_len = 200
        self.k_min = 21
        self.k_max = 141
        self.k_step = 10
        self.k_list = [21, 29, 39, 59, 79, 99, 119, 141]
        self.auto_k = True
        self.set_list_by_min_max_step = False
        self.min_count = 2
        self.has_popcnt = True
        self.hw_accel = True
        self.max_tip_len = -1
        self.no_mercy = False
        self.no_local = False
        self.bubble_level = 2
        self.merge_len = 20
        self.merge_similar = 0.95
        self.prune_level = 2
        self.prune_depth = 2
        self.num_cpu_threads = 0
        self.numa_node = None
        self.jobs_per_node = 1
        self.memory_budget_per_job = 0
        self.disconnect_ratio = 0.1
        self.low_local_ratio = 0.2
        self.cleaning_rounds = 5
        self.keep_tmp_files = False
        self.mem_flag = 1
        self.out_prefix = ''
        self.kmin_1pass = False
        self.pe1 = []
        self.pe2 = []
        self.pe12 = []
        self.se = []
        self.presets = ''
        self.verbose = False

    @property
    def log_file_name(self):
        if self.out_prefix == '':
            return os.path.join(self.out_dir, 'log')
        else:
            return os.path.join(self.out_dir, self.out_prefix + '.log')

    @property
    def option_file_name(self):
        return os.path.join(self.out_dir, 'options.json')

    @property
    def contig_dir(self):
        return os.path.join(self.out_dir, 'intermediate_contigs')

    @property
    def read_lib_path(self):
        return os.path.join(self.temp_dir, 'reads.lib')

    @property
    def megahit_core(self):
        if self.hw_accel:
            return software_info.megahit_core
        elif self.has_popcnt:
            return software_info.megahit_core_popcnt
        else:
            return software_info.megahit_core_no_hw_accel

    @property
    def host_mem(self):
        if self.memory <= 0:
            raise Usage('Please specify a positive number for -m flag.')
        elif self.memory < 1:
            try:
                total_mem = (_numa_reservation.memory_capacity
                             if _numa_reservation is not None else
                             detect_available_mem(
                                 None if self.numa_node == 'off' else self.numa_node))
                base_budget = math.floor(total_mem * self.memory)
            except Exception:
                raise Usage('Failed to detect available memory size, '
                            'please specify memory size in byte via -m option')
        else:
            base_budget = math.floor(self.memory)
        return resolve_job_memory_budget(
            base_budget, self.jobs_per_node, self.memory_budget_per_job)

    def dump(self):
        with open(self.option_file_name, 'w') as f:
            json.dump(self.__dict__, f)

    def load_for_continue(self):
        with open(self.option_file_name, 'r') as f:
            self.__dict__.update(json.load(f))


class Checkpoint:

    def __init__(self):
        self._current_checkpoint = 0
        self._logged_checkpoint = None
        self._file = None

    def set_file(self, file):
        self._file = file

    def __call__(self, func):
        def checked_or_call(*args, **kwargs):
            if self._logged_checkpoint is None or self._current_checkpoint > self._logged_checkpoint:
                func(*args, **kwargs)
                with open(self._file, 'a') as cpf:
                    print(str(self._current_checkpoint) + '\t' + 'done', file=cpf)
            else:
                logger.info('passing check point {0}'.format(self._current_checkpoint))
            self._current_checkpoint += 1

        return checked_or_call

    def load_for_continue(self):
        self._logged_checkpoint = -1
        if os.path.exists(self._file):
            with open(self._file, 'r') as f:
                for line in f:
                    a = line.strip().split()
                    if len(a) == 2 and a[1] == 'done':
                        self._logged_checkpoint = int(a[0])


software_info = SoftwareInfo()
opt = Options()
check_point = Checkpoint()
iterate_index_plan = None


def check_bin():
    if not os.path.exists(opt.megahit_core):
        raise Usage('Cannot find megahit_core, please recompile.')


def parse_option(argv):
    try:
        opts, args = getopt.getopt(argv, 'hm:o:r:t:v1:2:l:f',
                                   ['help',
                                    'read=',
                                    '12=',
                                    'memory=',
                                    'out-dir=',
                                    'min-contig-len=',
                                    'num-cpu-threads=',
                                    'numa-node=',
                                    'jobs-per-node=',
                                    'memory-budget-per-job=',
                                    'kmin-1pass',
                                    'k-min=',
                                    'k-max=',
                                    'k-step=',
                                    'k-list=',
                                    'num-cpu-threads=',
                                    'min-count=',
                                    'no-mercy',
                                    'no-local',
                                    'max-tip-len=',
                                    'bubble-level=',
                                    'prune-level=',
                                    'prune-depth=',
                                    'merge-level=',
                                    'disconnect-ratio=',
                                    'low-local-ratio=',
                                    'cleaning-rounds=',
                                    'keep-tmp-files',
                                    'tmp-dir=',
                                    'mem-flag=',
                                    'continue',
                                    'version',
                                    'verbose',
                                    'out-prefix=',
                                    'presets=',
                                    'test',
                                    'no-hw-accel',
                                    'force',
                                    # deprecated
                                    'max-read-len=',
                                    'no-low-local',
                                    'cpu-only',
                                    'gpu-mem=',
                                    'use-gpu'])
    except getopt.error as msg:
        raise Usage(software_info.megahit_version + '\n' + str(msg))
    if len(opts) == 0:
        raise Usage(software_info.megahit_version + '\n' + software_info.usage_message)

    for option, value in opts:
        if option in ('-h', '--help'):
            print(software_info.megahit_version + '\n' + software_info.usage_message)
            exit(0)
        elif option in ('-o', '--out-dir'):
            opt.out_dir = abspath(value)
        elif option in ('-m', '--memory'):
            opt.memory = float(value)
        elif option == '--min-contig-len':
            opt.min_contig_len = int(value)
        elif option in ('-t', '--num-cpu-threads'):
            opt.num_cpu_threads = int(value)
            if opt.num_cpu_threads <= 0:
                raise Usage('--num-cpu-threads must be greater than 0.')
        elif option == '--numa-node':
            if value in ('auto', 'off'):
                opt.numa_node = value
            else:
                try:
                    opt.numa_node = int(value)
                except ValueError:
                    raise Usage('--numa-node must be "auto", "off" or a non-negative '
                                'Linux NUMA node ID.')
        elif option == '--jobs-per-node':
            opt.jobs_per_node = int(value)
        elif option == '--memory-budget-per-job':
            opt.memory_budget_per_job = float(value)
        elif option == '--kmin-1pass':
            opt.kmin_1pass = True
        elif option == '--k-min':
            opt.k_min = int(value)
            opt.set_list_by_min_max_step = True
            opt.auto_k = False
        elif option == '--k-max':
            opt.k_max = int(value)
            opt.set_list_by_min_max_step = True
            opt.auto_k = False
        elif option == '--k-step':
            opt.k_step = int(value)
            opt.set_list_by_min_max_step = True
            opt.auto_k = False
        elif option == '--k-list':
            opt.k_list = list(map(int, value.split(',')))
            opt.k_list.sort()
            opt.auto_k = False
            opt.set_list_by_min_max_step = False
        elif option == '--min-count':
            opt.min_count = int(value)
        elif option == '--max-tip-len':
            opt.max_tip_len = int(value)
        elif option == '--merge-level':
            (opt.merge_len, opt.merge_similar) = list(map(float, value.split(',')))
            opt.merge_len = int(opt.merge_len)
        elif option == '--prune-level':
            opt.prune_level = int(value)
        elif option == '--prune-depth':
            opt.prune_depth = float(value)
        elif option == '--bubble-level':
            opt.bubble_level = int(value)
        elif option == '--no-mercy':
            opt.no_mercy = True
        elif option == '--no-local':
            opt.no_local = True
        elif option == '--disconnect-ratio':
            opt.disconnect_ratio = float(value)
        elif option == '--low-local-ratio':
            opt.low_local_ratio = float(value)
        elif option == '--cleaning-rounds':
            opt.cleaning_rounds = int(value)
        elif option == '--keep-tmp-files':
            opt.keep_tmp_files = True
        elif option == '--mem-flag':
            opt.mem_flag = int(value)
        elif option in ('-v', '--version'):
            print(software_info.megahit_version)
            exit(0)
        elif option == '--verbose':
            opt.verbose = True
        elif option == '--continue':
            opt.continue_mode = True
        elif option == '--out-prefix':
            opt.out_prefix = value
        elif option == '--tmp-dir':
            opt.temp_dir = abspath(value)
        elif option in ('--cpu-only', '-l', '--max-read-len', '--no-low-local',
                        '--use-gpu', '--gpu-mem'):
            print('option {0} is deprecated!'.format(option), file=sys.stderr)
            continue  # deprecated options, just ignore
        elif option in ('-r', '--read'):
            opt.se += [abspath(f) for f in value.split(',')]
        elif option == '-1':
            opt.pe1 += [abspath(f) for f in value.split(',')]
        elif option == '-2':
            opt.pe2 += [abspath(f) for f in value.split(',')]
        elif option == '--12':
            opt.pe12 += [abspath(f) for f in value.split(',')]
        elif option == '--presets':
            opt.presets = value
        elif option in ('-f', '--force'):
            opt.force_overwrite = True
        elif option == '--test':
            opt.test_mode = True
        elif option == '--no-hw-accel':
            opt.hw_accel = False
            opt.has_popcnt = False
        else:
            raise Usage('Invalid option {0}'.format(option))


def setup_output_dir():
    if not opt.out_dir:
        if opt.test_mode:
            opt.out_dir = tempfile.mkdtemp(prefix='megahit_test_')
        else:
            opt.out_dir = abspath('./megahit_out')

    check_point.set_file(os.path.join(opt.out_dir, 'checkpoints.txt'))

    if opt.continue_mode and not os.path.exists(opt.option_file_name):
        print('Cannot find {0}, switching to normal mode'.format(opt.option_file_name), file=sys.stderr)
        opt.continue_mode = False

    if opt.continue_mode:
        print('Continue mode activated. Ignore all options except for -o/--out-dir.', file=sys.stderr)
        opt.load_for_continue()
        check_point.load_for_continue()
    else:
        if not opt.force_overwrite and not opt.test_mode and os.path.exists(opt.out_dir):
            raise Usage(
                'Output directory ' + opt.out_dir +
                ' already exists, please change the parameter -o to another value to avoid overwriting.')

        if opt.temp_dir == '':
            opt.temp_dir = os.path.join(opt.out_dir, 'tmp')
        else:
            opt.temp_dir = tempfile.mkdtemp(dir=opt.temp_dir, prefix='megahit_tmp_')

    mkdir_if_not_exists(opt.out_dir)
    mkdir_if_not_exists(opt.temp_dir)
    mkdir_if_not_exists(opt.contig_dir)


def setup_logger():
    formatter = logging.Formatter('%(asctime)s - %(message)s', '%Y-%m-%d %H:%M:%S')

    file_handler = logging.FileHandler(opt.log_file_name, 'a')
    file_handler.setLevel(logging.DEBUG)
    file_handler.setFormatter(formatter)

    console = logging.StreamHandler()
    console.setLevel(logging.INFO)
    console.setFormatter(formatter)

    logger.setLevel(logging.DEBUG)
    logger.addHandler(file_handler)
    logger.addHandler(console)

    logger.info(software_info.megahit_version)


def check_and_correct_option():
    # set mode
    if opt.memory < 0:
        raise Usage('-m cannot be less than 0!')
    if (opt.numa_node not in (None, 'auto', 'off') and
            opt.numa_node < 0):
        raise Usage('--numa-node must be a non-negative Linux NUMA node ID.')
    if opt.jobs_per_node <= 0:
        raise Usage('--jobs-per-node must be greater than 0.')
    if (not math.isfinite(opt.memory_budget_per_job) or
            opt.memory_budget_per_job < 0):
        raise Usage('--memory-budget-per-job must be a finite non-negative '
                    'number of bytes.')

    if opt.presets != '':
        opt.auto_k = True

        if opt.presets == 'meta-sensitive':
            opt.min_count = 1
            opt.k_list = [21, 29, 39, 49, 59, 69, 79, 89, 99, 109, 119, 129, 141]
            opt.set_list_by_min_max_step = False
        elif opt.presets == 'meta-large':
            opt.min_count = 1
            opt.k_min = 27
            opt.k_max = 127
            opt.k_step = 10
            opt.set_list_by_min_max_step = True
        else:
            raise Usage('Invalid preset: ' + opt.presets)

    if opt.set_list_by_min_max_step:
        if opt.k_step <= 0:
            raise Usage('k-step must be greater than 0!')
        if opt.k_step % 2 == 1:
            raise Usage('k-step must be even number!')
        if opt.k_min > opt.k_max:
            raise Usage('Error: k_min > k_max!')

        opt.k_list = list()
        k = opt.k_min
        while k < opt.k_max:
            opt.k_list.append(k)
            k = k + opt.k_step
        opt.k_list.append(opt.k_max)

    if len(opt.k_list) == 0:
        raise Usage('k list should not be empty!')

    if opt.k_list[0] < 15 or opt.k_list[-1] > software_info.max_k_allowed:
        raise Usage('All k\'s should be in range [15, %d]' % software_info.max_k_allowed)

    for k in opt.k_list:
        if k % 2 == 0:
            raise Usage('All k must be odd number!')

    for i in range(1, len(opt.k_list)):
        if opt.k_list[i] - opt.k_list[i - 1] > 28:
            raise Usage('--k-step (adjacent k difference) must be <= 28')

    opt.k_min, opt.k_max = opt.k_list[0], opt.k_list[-1]

    if opt.k_max < opt.k_min:
        raise Usage('--k-min should not be larger than --k-max.')
    if opt.min_count <= 0:
        raise Usage('--min-count must be greater than 0.')
    elif opt.min_count == 1:
        opt.kmin_1pass = True
        opt.no_mercy = True
    if opt.prune_level < 0 or opt.prune_level > 3:
        raise Usage('--prune-level must be in 0-3.')
    if opt.merge_len < 0:
        raise Usage('--merge-level: length must be >= 0')
    if opt.merge_similar < 0 or opt.merge_similar > 1:
        raise Usage('--merge-level: similarity must be in [0, 1]')
    if opt.disconnect_ratio < 0 or opt.disconnect_ratio > 0.5:
        raise Usage('--disconnect-ratio should be in [0, 0.5].')
    if opt.low_local_ratio <= 0 or opt.low_local_ratio > 0.5:
        raise Usage('--low-local-ratio should be in (0, 0.5].')
    if opt.cleaning_rounds <= 0:
        raise Usage('--cleaning-rounds must be >= 1')
    if opt.num_cpu_threads < 0:
        raise Usage('--num-cpu-threads must be greater than 0.')
    if opt.num_cpu_threads > len(os.sched_getaffinity(0)):
        logger.warning('Maximum number of available CPU thread is %d.' % len(os.sched_getaffinity(0)))
        logger.warning('Number of thread is reset to the %d.' % len(os.sched_getaffinity(0)))
        opt.num_cpu_threads = len(os.sched_getaffinity(0))
    if opt.num_cpu_threads == 0:
        # In explicit NUMA-local mode, default to one worker per physical core.
        # Using every logical CPU would silently enable SMT and is rarely a
        # good default for the bandwidth-bound graph kernels.
        physical_cores = available_physical_cores()
        opt.num_cpu_threads = (
            physical_cores if opt.numa_node not in (None, 'off') and
            physical_cores is not None else len(os.sched_getaffinity(0)))
    if opt.prune_depth < 0 and opt.prune_level < 3:
        opt.prune_depth = opt.min_count
    if opt.bubble_level < 0:
        logger.warning('Reset bubble level to 0.')
        opt.bubble_level = 0
    if opt.bubble_level > 2:
        logger.warning('Reset bubble level to 2.')
        opt.bubble_level = 2


def find_test_data_path():
    script_path = software_info.script_path
    for path in [script_path,
                 os.path.join(script_path, '..'),
                 os.path.join(script_path, '../share/RabbitMA'),
                 os.path.join(script_path, '../share/megahit')]:
        test_data_dir = abspath(os.path.join(path, 'test_data'))
        if os.path.isdir(test_data_dir) and all(
                f in os.listdir(test_data_dir) for f in ['r1.il.fa.gz', 'r2.il.fa.bz2', 'r3_1.fa', 'r3_2.fa', 'r4.fa']):
            return test_data_dir
    raise Usage('Test data not found! Script path = {0}'.format(script_path))


def check_reads():
    if opt.test_mode:
        test_data_dir = find_test_data_path()
        opt.pe12 = [os.path.join(test_data_dir, 'r1.il.fa.gz'), os.path.join(test_data_dir, 'r2.il.fa.bz2')]
        opt.pe1 = [os.path.join(test_data_dir, 'r3_1.fa')]
        opt.pe2 = [os.path.join(test_data_dir, 'r3_2.fa')]
        opt.se = [os.path.join(test_data_dir, 'r4.fa'), os.path.join(test_data_dir, 'loop.fa')]

    if len(opt.pe1) != len(opt.pe2):
        raise Usage('Number of paired-end files not match!')
    for r in opt.pe1 + opt.pe2 + opt.se + opt.pe12:
        if not os.path.exists(r):
            raise Usage('Cannot find file ' + r)


def parse_linux_index_list(text):
    """Parse Linux cpulist/nodelist syntax such as ``0-3,8,10-11``."""
    result = set()
    for item in text.strip().split(','):
        if not item:
            continue
        bounds = item.split('-', 1)
        try:
            first = int(bounds[0])
            last = int(bounds[1]) if len(bounds) == 2 else first
        except ValueError:
            raise ValueError('invalid Linux index list: %s' % text.strip())
        if first < 0 or last < first:
            raise ValueError('invalid Linux index list: %s' % text.strip())
        result.update(range(first, last + 1))
    return result


def format_linux_index_list(indices):
    """Return a compact, deterministic Linux cpulist representation."""
    values = sorted(set(indices))
    ranges = []
    begin = None
    previous = None
    for value in values:
        if begin is None:
            begin = previous = value
        elif value == previous + 1:
            previous = value
        else:
            ranges.append(str(begin) if begin == previous else
                          '%d-%d' % (begin, previous))
            begin = previous = value
    if begin is not None:
        ranges.append(str(begin) if begin == previous else
                      '%d-%d' % (begin, previous))
    return ','.join(ranges)


def process_allowed_memory_nodes(status_path='/proc/self/status'):
    """Read the scheduler/cgroup memory-node allowance when Linux exposes it."""
    try:
        with open(status_path) as status:
            for line in status:
                if line.startswith('Mems_allowed_list:'):
                    return parse_linux_index_list(line.split(':', 1)[1])
    except (IOError, OSError, ValueError):
        pass
    return None


def discover_numa_cpu_sets(sysfs_root='/sys/devices/system/node',
                           status_path='/proc/self/status', affinity=None):
    """Map usable Linux NUMA IDs to CPUs in this process's current cpuset."""
    if affinity is None:
        try:
            affinity = os.sched_getaffinity(0)
        except (AttributeError, OSError):
            return {}
    affinity = set(affinity)
    allowed_memory = process_allowed_memory_nodes(status_path)
    result = {}
    for directory in glob.glob(os.path.join(sysfs_root, 'node[0-9]*')):
        suffix = os.path.basename(directory)[4:]
        if not suffix.isdigit():
            continue
        node = int(suffix)
        if allowed_memory is not None and node not in allowed_memory:
            continue
        try:
            with open(os.path.join(directory, 'cpulist')) as cpulist:
                cpus = parse_linux_index_list(cpulist.read()) & affinity
        except (IOError, OSError, ValueError):
            continue
        if cpus:
            result[node] = cpus
    return result


def detect_numa_node_memory(node,
                            sysfs_root='/sys/devices/system/node'):
    """Return one NUMA node's physical memory capacity in bytes."""
    path = os.path.join(sysfs_root, 'node%d' % node, 'meminfo')
    with open(path) as meminfo:
        for line in meminfo:
            fields = line.split()
            if 'MemTotal:' not in fields:
                continue
            index = fields.index('MemTotal:')
            value = int(fields[index + 1])
            unit = fields[index + 2].lower() if len(fields) > index + 2 else ''
            if unit == 'kb':
                return value * 1024
            if unit == 'mb':
                return value * 1024 * 1024
            if unit in ('', 'b'):
                return value
            raise ValueError('unsupported NUMA memory unit: %s' % unit)
    raise ValueError('MemTotal is missing from %s' % path)


def load_numa_library(library=None):
    """Use the relocatable release runtime, or the source install's system lib."""
    if library is None:
        bundled = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                               '..', 'lib', 'libnuma.so.1')
        library = bundled if os.path.isfile(bundled) else 'libnuma.so.1'
    return ctypes.CDLL(library, use_errno=True)


def bind_process_memory_to_numa_node(node, library=None, preferred=False):
    """Install a Linux memory policy before workers exist; children inherit it."""
    if sys.platform.find('linux') == -1:
        raise OSError('NUMA memory policy is only supported on Linux')
    try:
        libnuma = load_numa_library(library)
        set_mempolicy = libnuma.set_mempolicy
    except (OSError, AttributeError) as error:
        raise OSError('libnuma set_mempolicy is unavailable: %s' % error)

    bits_per_word = ctypes.sizeof(ctypes.c_ulong) * 8
    word_count = node // bits_per_word + 1
    mask_type = ctypes.c_ulong * word_count
    mask = mask_type()
    mask[node // bits_per_word] = 1 << (node % bits_per_word)
    set_mempolicy.argtypes = [ctypes.c_int,
                              ctypes.POINTER(ctypes.c_ulong),
                              ctypes.c_ulong]
    set_mempolicy.restype = ctypes.c_int
    ctypes.set_errno(0)
    # Explicit placement is strict. Automatic placement prefers local memory
    # but allows remote allocation when local memory is under pressure.
    if set_mempolicy(1 if preferred else 2, mask, word_count * bits_per_word) != 0:
        error_number = ctypes.get_errno()
        raise OSError(error_number, os.strerror(error_number))


def current_memory_policy(library=None):
    libnuma = load_numa_library(library)
    get_mempolicy = libnuma.get_mempolicy
    get_mempolicy.argtypes = [ctypes.POINTER(ctypes.c_int), ctypes.c_void_p,
                              ctypes.c_ulong, ctypes.c_void_p, ctypes.c_ulong]
    get_mempolicy.restype = ctypes.c_int
    mode = ctypes.c_int()
    if get_mempolicy(ctypes.byref(mode), None, 0, None, 0) != 0:
        error_number = ctypes.get_errno()
        raise OSError(error_number, os.strerror(error_number))
    return mode.value


def physical_core_cpu_sets(cpus, sysfs_root='/sys/devices/system/cpu'):
    """Keep SMT siblings together when reserving or counting physical cores."""
    result = {}
    for cpu in sorted(cpus):
        root = os.path.join(sysfs_root, 'cpu%d' % cpu, 'topology')
        with open(os.path.join(root, 'physical_package_id')) as stream:
            package = int(stream.read())
        with open(os.path.join(root, 'core_id')) as stream:
            core = int(stream.read())
        result.setdefault((package, core), set()).add(cpu)
    return result


class NumaReservation:
    """Cooperative physical-core leases, shared by this user's local instances.

    Lock files stay in place: unlinking an idle lock could create two distinct
    locking inodes. No process IDs are used; kernel file-description lifetime
    also covers children surviving an interrupted launcher.
    """

    def __init__(self, node, cpus, fds, memory_capacity):
        self.node = node
        self.cpus = cpus
        self.fds = fds
        self.memory_capacity = memory_capacity

    def close(self):
        for fd in self.fds:
            os.close(fd)
        self.fds = []

    @classmethod
    def acquire(cls, nodes, threads, capacities, minimum_memory=0, directory=None):
        import fcntl
        if directory is None:
            # /dev/shm is host-local on Linux; do not put coordination files
            # in a possibly shared job output directory or $TMPDIR.
            if not os.path.isdir('/dev/shm'):
                return None
            directory = '/dev/shm/rabbitma-numa-%d' % os.getuid()
        try:
            os.mkdir(directory, 0o700)
        except FileExistsError:
            pass
        directory_fd = os.open(directory, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
        locked, retained, guard = [], set(), None

        def open_lock(name):
            fd = os.open(name, os.O_RDWR | os.O_CREAT | os.O_NOFOLLOW,
                         0o600, dir_fd=directory_fd)
            info = os.fstat(fd)
            if (not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid()
                    or info.st_nlink != 1 or info.st_mode & 0o077):
                os.close(fd)
                raise OSError('unsafe NUMA reservation file')
            return fd

        try:
            info = os.fstat(directory_fd)
            if info.st_uid != os.getuid() or info.st_mode & 0o077:
                raise OSError('NUMA reservation directory must be private to this user')
            guard = open_lock('allocation.lock')
            deadline = time.monotonic() + 2
            while True:
                try:
                    fcntl.flock(guard, fcntl.LOCK_EX | fcntl.LOCK_NB)
                    break
                except BlockingIOError:
                    if time.monotonic() >= deadline:
                        return None
                    time.sleep(0.01)
            candidates = []
            for node, cores in sorted(nodes.items()):
                if len(cores) < threads or capacities[node] < minimum_memory:
                    continue
                free = []
                for key, cpus in sorted(cores.items()):
                    fd = open_lock('core-%d-%d.lock' % key)
                    try:
                        fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
                    except BlockingIOError:
                        os.close(fd)
                        continue
                    except Exception:
                        os.close(fd)
                        raise
                    locked.append(fd)
                    free.append((fd, cpus))
                if len(free) >= threads:
                    # Prefer an unused NUMA domain, then the least occupied
                    # domain. The coordinator serializes simultaneous starts.
                    candidates.append((len(cores) - len(free), node, free))
            if not candidates:
                return None
            _, node, free = min(candidates, key=lambda row: row[:2])
            selected = free[:threads]
            cpus = set().union(*(entry[1] for entry in selected))
            reservation = cls(node, cpus, [entry[0] for entry in selected], capacities[node])
            retained.update(reservation.fds)
            return reservation
        finally:
            for fd in locked:
                if fd not in retained:
                    os.close(fd)
            if guard is not None:
                os.close(guard)
            os.close(directory_fd)


def configure_automatic_numa_runtime():
    """Place an explicitly sized job inside its inherited CPU allocation."""
    global _numa_reservation
    if (not sys.platform.startswith('linux') or opt.num_cpu_threads <= 0
            or opt.jobs_per_node != 1 or _numa_reservation is not None
            or os.environ.get('MEGAHIT_DISABLE_AUTO_NUMA', '0') not in ('', '0')):
        return
    # Preserve explicit external CPU IDs and memory policies. Generic OpenMP
    # places (cores/threads/sockets) still work within the reserved CPU mask.
    places = os.environ.get('OMP_PLACES', '').strip().lower()
    if (places not in ('', 'cores', 'threads', 'sockets')
            or any(os.environ.get(name) for name in
                   ('GOMP_CPU_AFFINITY', 'KMP_AFFINITY', 'MEGAHIT_NUMA_NODE'))
            or os.environ.get('OMP_PROC_BIND', '').lower() == 'false'):
        logger.info('Automatic NUMA placement: preserving explicit CPU configuration')
        return
    reservation = None
    original_cpus = None
    affinity_changed = False
    try:
        if current_memory_policy() != 0:
            logger.info('Automatic NUMA placement: preserving inherited memory policy')
            return
        original_cpus = set(os.sched_getaffinity(0))
        cpu_sets = discover_numa_cpu_sets(affinity=original_cpus)
        nodes = {node: physical_core_cpu_sets(cpus) for node, cpus in cpu_sets.items()}
        threads = opt.num_cpu_threads
        capacities = {}
        for node, cores in nodes.items():
            with open('/sys/devices/system/node/node%d/cpulist' % node) as stream:
                all_cores = physical_core_cpu_sets(parse_linux_index_list(stream.read()))
            share = detect_numa_node_memory(node) * threads // len(all_cores)
            capacities[node] = min(share, detect_available_mem())
        minimum_memory = opt.memory if opt.memory >= 1 else 0
        if opt.memory_budget_per_job > 0:
            minimum_memory = min(minimum_memory or opt.memory_budget_per_job,
                                 opt.memory_budget_per_job)
        reservation = NumaReservation.acquire(nodes, threads, capacities, minimum_memory)
        if reservation is None:
            logger.info('Automatic NUMA placement: no single-node reservation fits; '
                        'keeping inherited CPU and memory placement')
            return
        os.sched_setaffinity(0, reservation.cpus)
        affinity_changed = True
        bind_process_memory_to_numa_node(reservation.node, preferred=True)
    except (OSError, AttributeError, ValueError, ImportError) as error:
        if reservation is not None:
            if affinity_changed:
                try:
                    os.sched_setaffinity(0, original_cpus)
                except OSError as restore_error:
                    # If a changing cpuset prevents rollback, retain the
                    # lease so another instance cannot reserve these cores.
                    _numa_reservation = reservation
                    logger.warning('Automatic NUMA memory placement unavailable: %s; '
                                   'retaining CPU reservation because restoring '
                                   'inherited affinity failed: %s' % (error, restore_error))
                    return
            reservation.close()
        logger.warning('Automatic NUMA placement unavailable: %s; '
                       'using inherited placement' % error)
        return
    _numa_reservation = reservation
    logger.info('Automatic NUMA placement: node %d, %d physical cores, CPUs %s; '
                'private memory prefers this node (remote fallback allowed); '
                'memory capacity for this CPU share %d bytes' %
                (reservation.node, threads, format_linux_index_list(reservation.cpus),
                 reservation.memory_capacity))


def resolve_numa_node(requested_node, available_nodes):
    if requested_node == 'auto':
        if len(available_nodes) != 1:
            raise ValueError('--numa-node auto requires the scheduler CPU '
                             'mask to intersect exactly one NUMA node; found '
                             '%d' % len(available_nodes))
        return next(iter(available_nodes))
    return requested_node


def configure_numa_runtime():
    """Restrict this launcher and all children to one explicit NUMA domain."""
    if opt.numa_node is None:
        configure_automatic_numa_runtime()
        return
    if opt.numa_node == 'off':
        return
    if opt.numa_node != 'auto' and opt.numa_node < 0:
        raise Usage('--numa-node must be a non-negative Linux NUMA node ID.')

    nodes = discover_numa_cpu_sets()
    try:
        opt.numa_node = resolve_numa_node(opt.numa_node, nodes)
    except ValueError as error:
        raise Usage(str(error))
    if opt.numa_node not in nodes:
        available = ','.join(map(str, sorted(nodes))) if nodes else 'none'
        raise Usage('NUMA node %d is not available in this job\'s CPU and '
                    'memory allocation (available nodes: %s).' %
                    (opt.numa_node, available))
    try:
        os.sched_setaffinity(0, nodes[opt.numa_node])
        selected_cpus = set(os.sched_getaffinity(0))
    except (AttributeError, OSError) as error:
        raise Usage('Failed to bind CPUs to NUMA node %d: %s' %
                    (opt.numa_node, error))
    if not selected_cpus:
        raise Usage('NUMA node %d has no CPUs in this job\'s allocation.' %
                    opt.numa_node)

    try:
        bind_process_memory_to_numa_node(opt.numa_node)
    except OSError as error:
        raise Usage('Failed to bind memory to NUMA node %d: %s' %
                    (opt.numa_node, error))

    os.environ['MEGAHIT_NUMA_NODE'] = str(opt.numa_node)
    logger.info('NUMA binding: node %d, CPUs %s; private allocations are '
                'restricted to this memory node' %
                (opt.numa_node, format_linux_index_list(selected_cpus)))


def _read_finite_memory_limit(path):
    try:
        with open(path) as memory_file:
            text = memory_file.read().strip()
    except (IOError, OSError):
        return None

    if not text or text == 'max':
        return None
    try:
        value = int(text)
    except ValueError:
        return None
    if value <= 0 or value >= (1 << 60):
        return None
    return value


def _minimum_limit_in_hierarchy(root, relative_path, limit_name):
    root = os.path.realpath(root)
    directory = os.path.realpath(
        os.path.join(root, relative_path.lstrip('/')))
    if directory != root and not directory.startswith(root + os.sep):
        return None

    result = None
    while True:
        value = _read_finite_memory_limit(
            os.path.join(directory, limit_name))
        if value is not None and (result is None or value < result):
            result = value
        if directory == root:
            break
        parent = os.path.dirname(directory)
        if parent == directory or len(parent) < len(root):
            break
        directory = parent
    return result


def detect_cgroup_memory_limit(cgroup_file='/proc/self/cgroup',
                               unified_root='/sys/fs/cgroup',
                               legacy_root='/sys/fs/cgroup/memory'):
    unified_path = None
    legacy_path = None
    try:
        with open(cgroup_file) as cgroups:
            for line in cgroups:
                fields = line.rstrip('\n').split(':', 2)
                if len(fields) != 3:
                    continue
                controllers = fields[1].split(',') if fields[1] else []
                if not controllers:
                    unified_path = fields[2]
                if 'memory' in controllers:
                    legacy_path = fields[2]
    except (IOError, OSError):
        return None

    limits = []
    if unified_path is not None:
        limit = _minimum_limit_in_hierarchy(
            unified_root, unified_path, 'memory.max')
        if limit is not None:
            limits.append(limit)
    if legacy_path is not None:
        limit = _minimum_limit_in_hierarchy(
            legacy_root, legacy_path, 'memory.limit_in_bytes')
        if limit is not None:
            limits.append(limit)
    return min(limits) if limits else None


def detect_available_mem(numa_node=None):
    try:
        psize = os.sysconf('SC_PAGE_SIZE')
        pcount = os.sysconf('SC_PHYS_PAGES')
        if psize < 0 or pcount < 0:
            raise SystemError
        total_memory = psize * pcount
    except ValueError:
        if sys.platform.find("darwin") != -1:
            total_memory = int(float(
                os.popen("sysctl hw.memsize").readlines()[0].split()[1]))
        elif sys.platform.find("linux") != -1:
            total_memory = int(float(
                os.popen("free").readlines()[1].split()[1]) * 1024)
        else:
            raise

    if sys.platform.find("linux") != -1:
        if numa_node is not None:
            total_memory = min(total_memory,
                               detect_numa_node_memory(numa_node))
        cgroup_limit = detect_cgroup_memory_limit()
        if cgroup_limit is not None:
            total_memory = min(total_memory, cgroup_limit)
    return total_memory


def resolve_job_memory_budget(base_budget, jobs_per_node,
                              memory_budget_per_job=0):
    """Resolve the explicit per-process shared-resource memory contract."""
    base_budget = int(base_budget)
    jobs_per_node = int(jobs_per_node)
    if base_budget <= 0 or jobs_per_node <= 0:
        raise ValueError('memory budget and jobs per node must be positive')
    if memory_budget_per_job > 0:
        return max(1, min(base_budget, math.floor(memory_budget_per_job)))
    return max(1, base_budget // jobs_per_node)


def cpu_dispatch():
    if not opt.hw_accel:
        logger.info('Using megahit_core without POPCNT and BMI2 support, '
                    'because --no-hw-accel option manually specified')
    else:
        has_hw_accel = check_output([opt.megahit_core, 'checkcpu'])

        if has_hw_accel == '1':
            logger.info('Using megahit_core with POPCNT and BMI2 support')
        else:
            opt.hw_accel = False
            has_popcnt = check_output([opt.megahit_core, 'checkpopcnt'])
            if has_popcnt == '1':
                opt.has_popcnt = True
                logger.info('Using megahit_core with POPCNT support')
            else:
                logger.info('Using megahit_core without POPCNT and BMI2 support, '
                        'because the features not detected by CPUID ')


def available_physical_cores():
    """Count package/core pairs in the process affinity mask when available."""
    try:
        affinity = os.sched_getaffinity(0)
        cores = set()
        for cpu in affinity:
            topology = '/sys/devices/system/cpu/cpu%d/topology' % cpu
            with open(os.path.join(topology, 'physical_package_id')) as f:
                package = int(f.read().strip())
            with open(os.path.join(topology, 'core_id')) as f:
                core = int(f.read().strip())
            cores.add((package, core))
        return len(cores) if cores else None
    except (AttributeError, IOError, OSError, ValueError):
        return None


def configure_openmp_runtime():
    """Choose topology-aware defaults while preserving explicit tuning."""
    physical_cores = available_physical_cores()
    if physical_cores is not None and 'MEGAHIT_PHYSICAL_CORES' not in os.environ:
        # Child kernels can use this for phase-specific SMT decisions.  In
        # particular, iterate is dominated by random read-only hash probes and
        # loses throughput once two workers share each physical core.
        os.environ['MEGAHIT_PHYSICAL_CORES'] = str(physical_cores)
    if 'OMP_PLACES' not in os.environ:
        os.environ['OMP_PLACES'] = 'cores'
    if 'OMP_PROC_BIND' not in os.environ:
        # One thread per physical core benefits from locality.  Once SMT
        # siblings are requested, spread the first wave across all cores and
        # sockets before placing the sibling wave; this avoids concentrating
        # bandwidth-bound graph workers on a subset of cache/memory domains.
        os.environ['OMP_PROC_BIND'] = (
            'spread' if physical_cores is not None and
            opt.num_cpu_threads > physical_cores else 'close')
    logger.info('OpenMP placement: OMP_PLACES=%s, OMP_PROC_BIND=%s' %
                (os.environ['OMP_PLACES'], os.environ['OMP_PROC_BIND']))


def configure_shared_node_runtime():
    memory_budget = opt.host_mem
    os.environ['MEGAHIT_JOBS_PER_NODE'] = str(opt.jobs_per_node)
    os.environ['MEGAHIT_MEMORY_BUDGET_PER_JOB'] = str(memory_budget)
    physical_cores = available_physical_cores()
    logger.info('Resource policy: %d job(s) share the visible resource '
                'domain; per-job memory budget %d bytes' %
                (opt.jobs_per_node, memory_budget))
    # This mask belongs to one process. Scheduler jobs often have disjoint
    # masks, so multiplying it by jobs_per_node would invent oversubscription.
    if (physical_cores is not None and
            opt.num_cpu_threads > physical_cores):
        logger.warning(
            '%d threads exceed this job\'s %d visible physical cores; SMT '
            'or CPU oversubscription is expected. RabbitMA will not '
            'silently change the requested thread count.' %
            (opt.num_cpu_threads, physical_cores))


def graph_prefix(kmer_k):
    mkdir_if_not_exists(os.path.join(opt.temp_dir, 'k' + str(kmer_k)))
    return os.path.join(opt.temp_dir, 'k' + str(kmer_k), str(kmer_k))


def contig_prefix(kmer_k):
    return os.path.join(opt.contig_dir, 'k' + str(kmer_k))


def remove_temp_after_build(kmer_k):
    for i in range(opt.num_cpu_threads):
        remove_if_exists(graph_prefix(kmer_k) + '.edges.' + str(i))
    for i in range(64):
        remove_if_exists(graph_prefix(kmer_k) + '.mercy_cand.' + str(i))
    for i in range(opt.num_cpu_threads):
        remove_if_exists(graph_prefix(kmer_k) + '.mercy.' + str(i))
    remove_if_exists(graph_prefix(kmer_k) + '.cand')


def remove_temp_after_assemble(kmer_k):
    for extension in ['w', 'last', 'isd', 'dn', 'f', 'mul', 'mul2']:
        remove_if_exists(graph_prefix(kmer_k) + '.' + extension)
    for i in range(opt.num_cpu_threads):
        remove_if_exists(graph_prefix(kmer_k) + '.sdbg.' + str(i))
    for extension in ['', '.info', '.mgb']:
        remove_if_exists(graph_prefix(kmer_k) + '.isolated.fa' + extension)
        remove_if_exists(graph_prefix(kmer_k) + '.bridges.fa' + extension)
    remove_if_exists(graph_prefix(kmer_k) + '.bridges.meta')


def inpipe_cmd(file_name):
    # FastxReader transparently reads gzip streams.  Keeping the path here
    # lets buildlib process independent libraries in parallel instead of
    # blocking dozens of external gzip processes on sequentially-read FIFOs.
    if file_name.endswith('.bz2'):
        return ['bzip2', '-cd', file_name]
    else:
        return []


def quote_library_path(file_name):
    # The internal reader accepts quoted and historical unquoted paths.
    # Quoting keeps spaces and shell metacharacters as ordinary path data.
    if '\n' in file_name or '\r' in file_name:
        raise Usage('Input and temporary paths cannot contain newlines.')
    return '"' + file_name.replace('\\', '\\\\').replace('"', '\\"') + '"'


def planned_iterate_anchor_geometry():
    """Choose an exact-index geometry before the library has been decoded.

    Anchor length affects representation size and speed, never which reads are
    accepted after exact verification.  The aggregate regular-input extent is
    therefore a safe early order-of-magnitude estimate of the key population;
    unlike CPU or cache probing, it keeps the choice portable across hosts.
    Unknown-size streams simply use the established post-build planner.
    """
    if (os.environ.get('MEGAHIT_DISABLE_ITERATE_INDEX') is not None or
            len(opt.k_list) < 2):
        return None
    window_len = min(64, opt.k_min + 1)
    input_bytes = 0
    saw_regular_input = False
    for path in opt.pe12 + opt.pe1 + opt.pe2 + opt.se:
        try:
            if os.path.isfile(path):
                input_bytes += os.path.getsize(path)
                saw_regular_input = True
        except OSError:
            pass
    if not saw_regular_input or input_bytes <= 0:
        return None
    information_bits = max(1, input_bytes.bit_length())
    anchor_len = min(31, window_len, (information_bits + 1) // 2)
    return anchor_len, window_len


@check_point
def create_library_file():
    with open(opt.read_lib_path, 'w') as lib:
        for i, file_name in enumerate(opt.pe12):
            print(file_name, file=lib)
            if inpipe_cmd(file_name):
                print('interleaved ' + quote_library_path(
                    os.path.join(opt.temp_dir, 'inpipe.pe12.' + str(i))), file=lib)
            else:
                print('interleaved ' + quote_library_path(file_name), file=lib)

        for i, (file_name1, file_name2) in enumerate(zip(opt.pe1, opt.pe2)):
            print(','.join([file_name1, file_name2]), file=lib)

            if inpipe_cmd(file_name1):
                f1 = os.path.join(opt.temp_dir, 'inpipe.pe1.' + str(i))
            else:
                f1 = file_name1

            if inpipe_cmd(file_name2):
                f2 = os.path.join(opt.temp_dir, 'inpipe.pe2.' + str(i))
            else:
                f2 = file_name2

            print('pe ' + quote_library_path(f1) + ' ' +
                  quote_library_path(f2), file=lib)

        for i, file_name in enumerate(opt.se):
            print(file_name, file=lib)
            if inpipe_cmd(file_name):
                print('se ' + quote_library_path(
                    os.path.join(opt.temp_dir, 'inpipe.se.' + str(i))), file=lib)
            else:
                print('se ' + quote_library_path(file_name), file=lib)


@check_point
def build_library():
    cmd = [opt.megahit_core, 'buildlib', opt.read_lib_path, opt.read_lib_path,
           str(opt.num_cpu_threads)]
    early_geometry = planned_iterate_anchor_geometry()
    if early_geometry is not None:
        cmd.extend([str(early_geometry[0]), str(early_geometry[1])])
    fifos = list()
    fifo_commands = list()
    pipes = list()

    def create_fifo(read_type, num, command):
        fifo_path = os.path.join(opt.temp_dir, 'inpipe.{0}.{1}'.format(read_type, num))
        remove_if_exists(fifo_path)
        os.mkfifo(fifo_path)
        fifos.append(fifo_path)
        fifo_commands.append((fifo_path, command))

    def start_fifo_writers(build_process):
        # Start decoders only after buildlib is alive.  Opening the writer then
        # synchronizes with the real reader without a shell or an O_RDWR FIFO
        # anchor that can lose early decoder output.
        for fifo_path, command in fifo_commands:
            while True:
                try:
                    fifo_fd = os.open(
                        fifo_path, os.O_WRONLY | os.O_NONBLOCK)
                    try:
                        os.set_blocking(fifo_fd, True)
                    except Exception:
                        os.close(fifo_fd)
                        raise
                    break
                except OSError as error:
                    if error.errno != errno.ENXIO:
                        raise
                    if build_process.poll() is not None:
                        raise RuntimeError(
                            'buildlib exited before opening ' + fifo_path)
                    time.sleep(0.01)
            try:
                p = launch_process(command, stdout=fifo_fd,
                                     start_new_session=True)
            finally:
                os.close(fifo_fd)
            pipes.append(p)

    try:
        # create inpipe
        for i in range(len(opt.pe12)):
            if inpipe_cmd(opt.pe12[i]):
                create_fifo('pe12', i, inpipe_cmd(opt.pe12[i]))

        for i in range(len(opt.pe1)):
            if inpipe_cmd(opt.pe1[i]):
                create_fifo('pe1', i, inpipe_cmd(opt.pe1[i]))

            if inpipe_cmd(opt.pe2[i]):
                create_fifo('pe2', i, inpipe_cmd(opt.pe2[i]))

        for i in range(len(opt.se)):
            if inpipe_cmd(opt.se[i]):
                create_fifo('se', i, inpipe_cmd(opt.se[i]))

        run_sub_command(cmd, 'Convert reads to binary library', verbose=True,
                        on_started=start_fifo_writers)

        for p in pipes:
            pipe_ret = p.wait()
            if pipe_ret != 0:
                logger.error('Error occurs when reading inputs')
                exit(pipe_ret)

    finally:
        for p in pipes:
            if p.poll() is None:
                os.killpg(p.pid, signal.SIGTERM)
        for f in fifos:
            remove_if_exists(f)


def get_max_read_len():
    ret = 0
    with open(opt.read_lib_path + '.lib_info') as read_info:
        for info in read_info.readlines()[2::2]:
            ret = max(ret, int(info.split()[2]))
    read_info.close()
    return ret


def set_max_k_by_lib():
    if not opt.auto_k or len(opt.k_list) == 1:
        return False

    max_read_len = get_max_read_len()
    new_k_list = [k for k in opt.k_list if k < max_read_len + 20]
    if not new_k_list:
        return False
    else:
        opt.k_list = new_k_list
        opt.k_min = opt.k_list[0]
        opt.k_max = opt.k_list[-1]
        return True


def prepare_iterate_index():
    """Build one exact read-occurrence index and fuse the first k transition.

    The representation is derived from the actual k schedule and library
    cardinality.  The index builder and the first iterative join consume the
    same decoded read stream, eliminating a complete library traversal.  All
    later rounds query the same exact index.  There is deliberately no fixed
    workload- or machine-specific k threshold.
    """
    global iterate_index_plan
    iterate_index_plan = None
    if os.environ.get('MEGAHIT_DISABLE_ITERATE_INDEX') is not None:
        logger.info('Reusable iterate index disabled by environment')
        return
    if len(opt.k_list) < 2:
        return

    # Exact verification currently uses a four-word packed window.  This is a
    # representation limit, not a workload-tuned threshold.
    max_exact_window = 64
    window_len = min(max_exact_window, opt.k_min + 1)
    eligible_rounds = sum(1 for k in opt.k_list[:-1]
                          if k + 1 >= window_len)
    if eligible_rounds == 0:
        logger.info('Reusable iterate index skipped: no eligible later k round')
        return

    try:
        with open(opt.read_lib_path + '.lib_info') as read_info:
            fields = read_info.readline().split()
            total_bases = int(fields[0])
        packed_bytes = os.path.getsize(opt.read_lib_path + '.bin')
    except (IOError, OSError, ValueError, IndexError):
        logger.warning('Reusable iterate index skipped: read metadata unavailable')
        return

    # An exact a-mer has 2a information bits.  Pick the smallest domain whose
    # cardinality covers the input base population, capped only by the 64-bit
    # key representation and the exact window itself.  This yields a=19 for a
    # 100-Gbp library without naming that dataset or consulting CPU topology.
    early_geometry = planned_iterate_anchor_geometry()
    if early_geometry is None:
        information_bits = max(1, total_bases.bit_length())
        anchor_len = min(31, window_len, (information_bits + 1) // 2)
    else:
        anchor_len, early_window_len = early_geometry
        if early_window_len != window_len:
            raise RuntimeError('iterate-index geometry changed after buildlib')
    minimizer_span = window_len - anchor_len + 1

    # Construction briefly holds the external occurrence stream and compact
    # index together.  A conservative minimizer-density estimate avoids
    # exhausting a small temporary filesystem; insufficient space simply
    # preserves the exact full-scan implementation.
    expected_anchors = (2 * total_bases + minimizer_span) // \
                       (minimizer_span + 1)
    estimated_workspace = packed_bytes + expected_anchors * 16
    try:
        fs = os.statvfs(opt.temp_dir)
        free_bytes = fs.f_bavail * fs.f_frsize
    except (AttributeError, OSError):
        free_bytes = estimated_workspace
    if estimated_workspace > free_bytes:
        logger.warning('Reusable iterate index skipped: estimated workspace '
                       '%d bytes exceeds %d free bytes' %
                       (estimated_workspace, free_bytes))
        return

    # Bound scratch by both the user's global limit and the problem size.  The
    # builder internally allocates memory tokens per partition, so this is a
    # resource budget rather than a dataset-specific mode switch.
    memory_budget = max(1, min(opt.host_mem, max(1, packed_bytes // 2)))
    prefix = os.path.join(opt.temp_dir, 'iterate.read_index')
    ready_path = prefix + '.ready'
    read_stat = os.stat(opt.read_lib_path + '.bin')
    signature = {
        'read_size': read_stat.st_size,
        'read_mtime_ns': getattr(read_stat, 'st_mtime_ns',
                                 int(read_stat.st_mtime * 1000000000)),
        'anchor_len': anchor_len,
        'window_len': window_len,
        'first_k': opt.k_min,
        'first_step': opt.k_list[1] - opt.k_min,
        'fused_first_iteration': True,
    }

    ready = False
    prefetched_first_iteration = False
    try:
        with open(ready_path) as ready_file:
            ready_metadata = json.load(ready_file)
            ready = (all(ready_metadata.get(key) == value
                         for key, value in signature.items()) and
                     os.path.exists(prefix + '.ridx.info'))
            prefetched_first_iteration = (
                ready and ready_metadata.get('prefetched_first_iteration') and
                os.path.exists(graph_prefix(opt.k_list[1]) + '.edges.info') and
                os.path.exists(graph_prefix(opt.k_list[1]) + '.edges.0'))
    except (IOError, OSError, ValueError):
        pass

    if not ready:
        for path in glob.glob(prefix + '.ridx.*') + [ready_path]:
            try:
                os.remove(path)
            except OSError:
                pass
        build_cmd = [opt.megahit_core, 'read-index',
                     '-r', opt.read_lib_path + '.bin',
                     '-o', prefix,
                     '-c', contig_prefix(opt.k_min) + '.contigs.fa',
                     '-b', contig_prefix(opt.k_min) + '.bubble_seq.fa',
                     '-a', str(anchor_len),
                     '-w', str(window_len),
                     '-k', str(opt.k_min),
                     '-s', str(opt.k_list[1] - opt.k_min),
                     '-e', graph_prefix(opt.k_list[1]),
                     '-t', str(opt.num_cpu_threads),
                     '-m', str(memory_budget)]
        ret_code = run_sub_command_status(
            build_cmd,
            'Build reusable exact read index and fuse k = %d to %d ' %
            (opt.k_min, opt.k_list[1]))
        if ret_code != 0:
            logger.warning('Fused index construction failed; retrying the '
                           'persistent index without first-round fusion')
            for path in (glob.glob(prefix + '.ridx.*') +
                         glob.glob(prefix + '.ridx.tmp*') +
                         glob.glob(graph_prefix(opt.k_list[1]) + '.edges.*')):
                try:
                    os.remove(path)
                except OSError:
                    pass
            build_cmd = [opt.megahit_core, 'read-index',
                         '-r', opt.read_lib_path + '.bin',
                         '-o', prefix,
                         '-a', str(anchor_len),
                         '-w', str(window_len),
                         '-t', str(opt.num_cpu_threads),
                         '-m', str(memory_budget)]
            ret_code = run_sub_command_status(
                build_cmd,
                'Build reusable exact read index for %d eligible k rounds ' %
                eligible_rounds)
            if ret_code != 0:
                logger.warning('Reusable iterate index construction failed; '
                               'using exact full-read scans')
                for path in (glob.glob(prefix + '.ridx.*') +
                             glob.glob(prefix + '.ridx.tmp*')):
                    try:
                        os.remove(path)
                    except OSError:
                        pass
                return
        else:
            prefetched_first_iteration = True
        ready_metadata = dict(signature)
        ready_metadata['prefetched_first_iteration'] = \
            prefetched_first_iteration
        with open(ready_path, 'w') as ready_file:
            json.dump(ready_metadata, ready_file)
    else:
        logger.info('Reusing completed exact read index%s' %
                    (' and first iterative edge set'
                     if prefetched_first_iteration else ''))

    iterate_index_plan = {
        'prefix': prefix,
        'anchor_len': anchor_len,
        'window_len': window_len,
        'memory_budget': memory_budget,
        'prefetched_first_k': (opt.k_min if prefetched_first_iteration
                               else None),
    }
    logger.info('Iterate join planner: exact index window %d, anchor %d, '
                '%d eligible rounds, memory budget %d bytes' %
                (window_len, anchor_len, eligible_rounds, memory_budget))


@check_point
def build_first_graph_1pass(option):
    cmd = [opt.megahit_core, 'read2sdbg'] + option
    if not opt.no_mercy:
        cmd.append('--need_mercy')

    run_sub_command(cmd, 'Extracting solid (k+1)-mers and building sdbg for k = %d' % opt.k_min)

    if not opt.keep_tmp_files:
        remove_temp_after_build(opt.k_min)


@check_point
def count_mink(option):
    cmd = [opt.megahit_core, 'count'] + option
    run_sub_command(cmd, 'Extract solid (k+1)-mers for k = %d ' % opt.k_min)


def build_first_graph():
    common_option = ['-k', str(opt.k_min),
                     '-m', str(opt.min_count),
                     '--host_mem', str(opt.host_mem),
                     '--mem_flag', str(opt.mem_flag),
                     '--output_prefix', graph_prefix(opt.k_min),
                     '--num_cpu_threads', str(opt.num_cpu_threads),
                     '--read_lib_file', opt.read_lib_path]

    if not opt.kmin_1pass:
        count_mink(common_option)
        build_graph(opt.k_min, 0)
    else:
        build_first_graph_1pass(common_option)


@check_point
def build_graph(kmer_k, kmer_from):
    build_comm_opt = ['--host_mem', str(opt.host_mem),
                      '--mem_flag', str(opt.mem_flag),
                      '--output_prefix', graph_prefix(kmer_k),
                      '--num_cpu_threads', str(opt.num_cpu_threads),
                      '-k', str(kmer_k),
                      '--kmer_from', str(kmer_from)]

    build_cmd = [opt.megahit_core, 'seq2sdbg'] + build_comm_opt
    if os.environ.get('MEGAHIT_EXPERIMENTAL_CONTIG_BRIDGES') == '1':
        build_cmd.append('--bridge_contigs')
    elif os.environ.get('MEGAHIT_EXPERIMENTAL_STABLE_CONTIGS') == '1':
        build_cmd.append('--carry_stable_contigs')

    file_size = 0

    if os.path.exists(graph_prefix(kmer_k) + '.edges.0'):
        build_cmd += ['--input_prefix', graph_prefix(kmer_k)]
        file_size += os.path.getsize(graph_prefix(kmer_k) + '.edges.0')
        tid = 1
        while os.path.exists(graph_prefix(kmer_k) + '.edges.' + str(tid)):
            file_size += os.path.getsize(graph_prefix(kmer_k) + '.edges.' + str(tid))
            tid += 1

    if os.path.exists(contig_prefix(kmer_from) + '.addi.fa'):
        build_cmd += ['--addi_contig', contig_prefix(kmer_from) + '.addi.fa']
        file_size += os.path.getsize(contig_prefix(kmer_from) + '.addi.fa')

    if os.path.exists(contig_prefix(kmer_from) + '.local.fa'):
        build_cmd += ['--local_contig', contig_prefix(kmer_from) + '.local.fa']
        file_size += os.path.getsize(contig_prefix(kmer_from) + '.local.fa')

    if os.path.exists(contig_prefix(kmer_from) + '.contigs.fa'):
        build_cmd += ['--contig', contig_prefix(kmer_from) + '.contigs.fa']
        build_cmd += ['--bubble', contig_prefix(kmer_from) + '.bubble_seq.fa']

    if file_size == 0 and kmer_from != 0:
        raise EarlyTerminate(kmer_from)

    if not opt.no_mercy and kmer_k == opt.k_min:
        build_cmd.append('--need_mercy')

    run_sub_command(build_cmd, 'Build graph for k = %d ' % kmer_k)

    if not opt.keep_tmp_files:
        remove_temp_after_build(kmer_k)


@check_point
def iterate(cur_k, step):
    next_k = cur_k + step
    if (iterate_index_plan is not None and
            iterate_index_plan.get('prefetched_first_k') == cur_k and
            os.path.exists(graph_prefix(next_k) + '.edges.info') and
            os.path.exists(graph_prefix(next_k) + '.edges.0')):
        logger.info('Reusing iterative edges fused into read-index build from '
                    'k = %d to %d' % (cur_k, next_k))
        return
    if (iterate_index_plan is not None and
            cur_k + 1 >= iterate_index_plan['window_len']):
        index_cmd = [opt.megahit_core, 'read-index',
                     '-r', opt.read_lib_path + '.bin',
                     '--index_prefix', iterate_index_plan['prefix'],
                     '-c', contig_prefix(cur_k) + '.contigs.fa',
                     '-b', contig_prefix(cur_k) + '.bubble_seq.fa',
                     '-t', str(opt.num_cpu_threads),
                     '-a', str(iterate_index_plan['anchor_len']),
                     '-w', str(iterate_index_plan['window_len']),
                     '-k', str(cur_k),
                     '-s', str(step),
                     '-m', str(iterate_index_plan['memory_budget']),
                     '-e', graph_prefix(next_k)]
        ret_code = run_sub_command_status(
            index_cmd,
            'Query reusable read index from k = %d to %d ' %
            (cur_k, next_k))
        if ret_code == 0:
            return
        # The index is only a different exact join order.  Resource pressure,
        # an unexpectedly dense candidate set, or a damaged temporary index
        # must not make assembly fail when the original streaming join remains
        # available.
        logger.warning('Indexed iterate join failed for k = %d; falling back '
                       'to exact full-read scan' % cur_k)

    iterate_cmd = [opt.megahit_core, 'iterate',
                   '-c', contig_prefix(cur_k) + '.contigs.fa',
                   '-b', contig_prefix(cur_k) + '.bubble_seq.fa',
                   '-t', str(opt.num_cpu_threads),
                   '-k', str(cur_k),
                   '-s', str(step),
                   '-o', graph_prefix(next_k),
                   '-r', opt.read_lib_path + '.bin']

    run_sub_command(iterate_cmd, 'Extract iterative edges from k = %d to %d ' % (cur_k, next_k))


@check_point
def assemble(cur_k):
    min_standalone = max(min(opt.k_max * 3 - 1, int(opt.min_contig_len * 1.5)), opt.min_contig_len)
    if opt.max_tip_len >= 0:
        min_standalone = max(opt.max_tip_len + opt.k_max - 1, opt.min_contig_len)

    assembly_cmd = [opt.megahit_core, 'assemble',
                    '-s', graph_prefix(cur_k),
                    '-o', contig_prefix(cur_k),
                    '-t', str(opt.num_cpu_threads),
                    '--host_mem', str(opt.host_mem),
                    '--min_standalone', str(min_standalone),
                    '--prune_level', str(opt.prune_level),
                    '--merge_len', str(int(opt.merge_len)),
                    '--merge_similar', str(opt.merge_similar),
                    '--cleaning_rounds', str(opt.cleaning_rounds),
                    '--disconnect_ratio', str(opt.disconnect_ratio),
                    '--low_local_ratio', str(opt.low_local_ratio),
                    '--min_depth', str(opt.prune_depth),
                    '--bubble_level', str(opt.bubble_level)]

    if opt.max_tip_len == -1 and cur_k * 3 - 1 > opt.min_contig_len * 1.5:
        assembly_cmd += ['--max_tip_len', str(max(1, opt.min_contig_len * 1.5 + 1 - cur_k))]
    else:
        assembly_cmd += ['--max_tip_len', str(opt.max_tip_len)]

    if cur_k < opt.k_max:
        assembly_cmd.append('--careful_bubble')

    if cur_k == opt.k_max:
        assembly_cmd.append('--is_final_round')

    if opt.no_local:
        assembly_cmd.append('--output_standalone')

    run_sub_command(assembly_cmd, 'Assemble contigs from SdBG for k = %d' % cur_k)

    if (not opt.keep_tmp_files) and (cur_k != opt.k_max):
        remove_temp_after_assemble(cur_k)


@check_point
def local_assemble(cur_k, kmer_to):
    la_cmd = [opt.megahit_core, 'local',
              '-c', contig_prefix(cur_k) + '.contigs.fa',
              '-l', opt.read_lib_path,
              '-t', str(opt.num_cpu_threads),
              '-o', contig_prefix(cur_k) + '.local.fa',
              '--kmax', str(kmer_to)]
    run_sub_command(la_cmd, 'Local assembly for k = %d' % cur_k)


@check_point
def merge_final(final_k):
    logger.info('Merging to output final contigs ')
    final_contig_name = os.path.join(opt.out_dir, 'final.contigs.fa')
    if opt.out_prefix != '':
        final_contig_name = os.path.join(opt.out_dir, opt.out_prefix + '.contigs.fa')

    final_inputs = sorted(glob.glob(os.path.join(opt.contig_dir, '*.final.contigs.fa')))
    final_inputs.append(contig_prefix(final_k) + '.contigs.fa')
    with open(final_contig_name, 'w') as final_contigs:
        # Internal contigs may be stored in a compact .mgb sidecar with an
        # empty FASTA completion marker.  Let filterbylen open each logical
        # path so early termination and normal final-k merging share the same
        # packed/plain streaming path.  Passing argv directly also avoids the
        # shell wildcard and quoting ambiguities of the historical pipeline.
        merge_cmd = [opt.megahit_core, 'filterbylen', str(opt.min_contig_len)] + final_inputs
        p = launch_process(merge_cmd, stdout=final_contigs, stderr=subprocess.PIPE)
        _, log = p.communicate()
        logger.info(log.rstrip().decode('utf-8'))
        ret_code = p.wait()

    if ret_code != 0:
        logger.error('Error occurs when merging final contigs, please refer to %s for detail' % opt.log_file_name)
        logger.error('Exit code %d' % ret_code)
        exit(ret_code)


def run_sub_command_status(cmd, msg, verbose=False, on_started=None):
    if opt.verbose:
        verbose = True
    logger.info(msg)
    logger.debug('command %s' % ' '.join(cmd))

    p = launch_process(cmd, stderr=subprocess.PIPE)

    try:
        if on_started is not None:
            on_started(p)
        while True:
            raw_line = p.stderr.readline()
            if raw_line == b'':
                break
            line = raw_line.rstrip()
            if line:
                if verbose:
                    logger.info(line)
                else:
                    logger.debug(line)

        ret_code = p.wait()
        return ret_code
    except KeyboardInterrupt:
        p.terminate()
        p.wait()
        exit(signal.SIGINT)
    except Exception:
        p.terminate()
        p.wait()
        raise


def run_sub_command(cmd, msg, verbose=False, on_started=None):
    ret_code = run_sub_command_status(cmd, msg, verbose, on_started)
    if ret_code != 0:
        logger.error('Error occurs, please refer to %s for detail' % opt.log_file_name)
        logger.error('Command: %s; Exit code %d' % (' '.join(cmd), ret_code))
        exit(ret_code)


def main(argv=None):
    global _numa_reservation
    if argv is None:
        argv = sys.argv

    try:
        start_time = time.time()
        check_bin()
        parse_option(argv[1:])
        setup_output_dir()
        setup_logger()

        configure_numa_runtime()
        check_and_correct_option()

        check_reads()
        cpu_dispatch()
        configure_openmp_runtime()
        configure_shared_node_runtime()
        opt.dump()

        create_library_file()
        build_library()

        if set_max_k_by_lib():
            logger.info('k-max reset to: %d ' % opt.k_max)

        logger.info('Start assembly. Number of CPU threads %d ' % opt.num_cpu_threads)
        logger.info('k list: %s ' % ','.join(map(str, opt.k_list)))
        logger.info('Memory used: %d' % opt.host_mem)

        build_first_graph()
        assemble(opt.k_min)
        prepare_iterate_index()

        cur_k = opt.k_min
        next_k_idx = 0

        try:
            while cur_k < opt.k_max:
                next_k_idx += 1
                next_k = opt.k_list[next_k_idx]
                k_step = next_k - cur_k

                if not opt.no_local:
                    local_assemble(cur_k, next_k)

                iterate(cur_k, k_step)
                build_graph(next_k, cur_k)

                assemble(next_k)
                cur_k = next_k
            merge_final(opt.k_max)

        except EarlyTerminate as et:
            merge_final(et.kmer_size)

        if not opt.keep_tmp_files and os.path.exists(opt.temp_dir):
            shutil.rmtree(opt.temp_dir)

        open(os.path.join(opt.out_dir, 'done'), 'w').close()

        if not opt.keep_tmp_files and opt.test_mode:
            shutil.rmtree(opt.out_dir)

        logger.info('ALL DONE. Time elapsed: %f seconds ' % (time.time() - start_time))

    except Usage as usg:
        print(sys.argv[0].split('/')[-1] + ': ' + str(usg.msg), file=sys.stderr)
        exit(1)
    finally:
        if _numa_reservation is not None:
            _numa_reservation.close()
            _numa_reservation = None


if __name__ == '__main__':
    main()
